name: renew

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_DOMAIN: ${{ vars.DOMAIN }}
          CYPRESS_EMAILS: ${{ vars.emails }}
          CYPRESS_COUPON: ${{ vars.COUPON }}
          CYPRESS_PASSWORD: ${{ secrets.PASSWORD }}